### ISSUE TITLE
Values from VRC700 not shown

### ISSUE THREAD

**Issue by kirk-loeten** [csowada/ebus-configuration#11]
### Your Issue

In Things "Vaillant VRC 700 general (15)" many channels shows NaN. I think it is a new software version of the VRC700.

### Your Heating System

Vailant VWF 58 - 118/4 (Heatpump)
VRC700/2 Controller
openHabian 2.5.4-1 on Raspberry Pi 3 B
adapter eBus (https://wiki.fhem.de/wiki/EBUS, potentionmeter adjustment with Linux Mint)

### An example telegram
`2020-05-09 21:51:04.761 [bus notice] <1008b51101018900093e3c500eff5c0000ff1700`
`2020-05-09 21:51:05.027 [bus notice] <1076b5110101160009ff3c500eff5c0000ff6400`
`2020-05-09 21:51:05.298 [bus notice] <1076b512030f0201510007e60200008017057d00`
`2020-05-09 21:51:05.573 [bus notice] <1008b51009000000ffffff070000520001019a00`
`2020-05-09 21:51:05.844 [bus notice] <1076b51009000000ffffff010000850001019a00`
`2020-05-09 21:51:14.734 [bus notice] <1008b51101018900093e3c500eff5c0000ff1700`
`2020-05-09 21:51:15.001 [bus notice] <1076b5110101160009ff3c500eff5c0000ff6400`
`2020-05-09 21:51:15.272 [bus notice] <1076b512030f0201510007e60200008017057d00`
`2020-05-09 21:51:15.546 [bus notice] <1008b51009000000ffffff070000520001019a00`
`2020-05-09 21:51:15.817 [bus notice] <1076b51009000000ffffff010000850001019a00`
`2020-05-09 21:51:24.747 [bus notice] <1008b51101018900093e3c500eff5c0000ff1700`
`2020-05-09 21:51:25.014 [bus notice] <1076b5110101160009ff3c500eff5c0000ff6400`
`2020-05-09 21:51:25.285 [bus notice] <1076b512030f0201510007e5020000801705e100`
`2020-05-09 21:51:25.558 [bus notice] <1008b51009000000ffffff070000520001019a00`
`2020-05-09 21:51:25.829 [bus notice] <1076b51009000000ffffff010000850001019a00`
see log files

### Your Device Table or master/slave addresses
```
Thing UID                                | Label                                    | Type      
----------------------------------+------------------------------------------+-----------
ebus:vrc700_zone1:68997b4c:15            | Vaillant VRC 700 zone 1 (15)             | node      
ebus:vrc700_zone2:68997b4c:15            | Vaillant VRC 700 zone 2 (15)             | node      
ebus:vrc700_hwc:68997b4c:15              | Vaillant VRC 700 hot water circuit (15)  | node      
ebus:vrc700_vac:68997b4c:15              | Vaillant VRC 700 (H)VAC (15)             | node      
ebus:std:68997b4c:08                     | eBUS Standard (08)                       | node      
ebus:bai:b209582a                        | Vaillant BAI00                           | node      
ebus:std:68997b4c:76                     | eBUS Standard (76)                       | node      
ebus:std:68997b4c:04                     | eBUS Standard (04)                       | node      
ebus:std:68997b4c:15                     | eBUS Standard (15)                       | node      
ebus:vrc700_hc2:68997b4c:15              | Vaillant VRC 700 heating circuit 2 (15)  | node      
ebus:vrc700_general:68997b4c:15          | Vaillant VRC 700 general (15)            | node      
ebus:bridge:68997b4c                     | eBUS Bridge                              | bridge    
ebus:vrc700_hc1:68997b4c:15              | Vaillant VRC 700 heating circuit 1 (15)  | nodesee 
```
Picture

...
[ebus-resolved.txt](https://github.com/csowada/ebus-configuration/files/4604692/ebus-resolved.txt)
[ebus-unresolved.txt](https://github.com/csowada/ebus-configuration/files/4604693/ebus-unresolved.txt)
![Slaves76-04-15](https://user-images.githubusercontent.com/35734454/81486480-5be79300-9255-11ea-86bd-593fcdc588a3.png)
![Slave08](https://user-images.githubusercontent.com/35734454/81486492-6a35af00-9255-11ea-96d3-01335b9d81e2.png)
![slave15_example](https://user-images.githubusercontent.com/35734454/81486497-715cbd00-9255-11ea-9598-a338646b26d5.png)

**Comment by mwildbolz** [comment]
Many of them show NaN because there are no values present in underlying ebusd.
You have to read/poll those values...

**Comment by kirk-loeten** [comment]
Ok it works. But i didn't fund some informations about that.
![Bildschirmfoto 2020-06-21 um 21 08 51](https://user-images.githubusercontent.com/35734454/85232968-a0914d00-b403-11ea-96c9-f4d53b7d1dce.png)
